# Generated by Django 3.0.7 on 2021-06-21 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20210617_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 20, 39, 36, 105669)),
        ),
    ]
