# Generated by Django 3.2.4 on 2021-07-04 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0016_alter_upload_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 0, 36, 18, 641056)),
        ),
    ]
