# Generated by Django 3.2.4 on 2021-08-07 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0021_auto_20210806_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 23, 56, 6, 389180)),
        ),
    ]
