# Generated by Django 3.2.4 on 2021-08-08 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0022_alter_upload_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 8, 15, 1, 39, 751136)),
        ),
    ]
